In [ ]:
#Concatenation
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))


In [ ]:
#transpose and flatten
import numpy
N,M = map(int, input().split())
arr = numpy.array([input().split() for _ in range(N)],int)
print(arr.transpose())
print(arr.flatten())

In [3]:
#shape and reshape
import numpy
arr = numpy.array([input().split()],int)
arr.shape = (3,3)
print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Arrays
import numpy
def arrays(arr):
    return numpy.array(arr[::-1],float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

In [ ]:
#map and lambda function
cube = lambda x: x**3 # complete the lambda function 

def fibonacci(n):
    lis = [0,1]
    for i in range(2,n):
        lis.append(lis[i-2] + lis[i-1])
    return(lis[0:n])
    # return a list of fibonacci numbers
      


if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))